In [ ]:
#1.	Write a python method that adds 2 to the even numbers and 3 to the odd numbers in the list of values between 1 to 100?
def add():
  a= []
  for num in range(1,101):
    if num % 2 == 0:
      a.append(num+2)
    else:
      a.append(num+3)
  return a
a_list=add()
print(a_list)

[4, 4, 6, 6, 8, 8, 10, 10, 12, 12, 14, 14, 16, 16, 18, 18, 20, 20, 22, 22, 24, 24, 26, 26, 28, 28, 30, 30, 32, 32, 34, 34, 36, 36, 38, 38, 40, 40, 42, 42, 44, 44, 46, 46, 48, 48, 50, 50, 52, 52, 54, 54, 56, 56, 58, 58, 60, 60, 62, 62, 64, 64, 66, 66, 68, 68, 70, 70, 72, 72, 74, 74, 76, 76, 78, 78, 80, 80, 82, 82, 84, 84, 86, 86, 88, 88, 90, 90, 92, 92, 94, 94, 96, 96, 98, 98, 100, 100, 102, 102]


In [ ]:
#Python program that calculates the mean of numbers in a list between 250 to 500?
L1=range(250,501)
total=sum(L1)
count=len(L1)
mean=total/count
mean

375.0

In [ ]:
#Python code to create ones and zeros of shape 5x10 using NumPy array? And create two 1D arrays of shape 3x1 and find dot product of it?
import numpy as np
a= np.zeros((5,10))
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
b=np.ones((5,10))
b

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
a= np.array([[1],[2],[3]])
b= np.array([[3],[2],[1]])
dot_product=np.dot(a.flatten(),b.flatten())
print(dot_product)

10


In [ ]:
#Write a program to find a minimum of three numbers in a list [453,567,212]
L1=[453,567,212]
min_num=min(L1)
min_num

TypeError: ignored

In [ ]:
#5.	Write a Python program that creates a 2D NumPy array called ‘arr’ with dimensions 3x4, filled with integers between 1 and 10 (inclusive). Calculate and print the mean value of the array.


In [ ]:
import numpy as np
arr= np.array([[1,2,3,4],[5,6,7,8],[9,10,1,2]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10,  1,  2]])

In [ ]:
arr.ndim

2

In [ ]:
arr.shape

(3, 4)

In [ ]:
mean_value = np.mean(arr)
mean_value

4.833333333333333

In [ ]:
#6.	Write a python program to find factorial of 5 : fact(5) = 5x4x3x2x1
factorial=1
for i in range (1,5+1):
  factorial=factorial*i
factorial

120

In [ ]:
#Write a Python program to reverse a string?
s='srilekha'
reversed_s=s[::-1]
reversed_s

'ahkelirs'

In [ ]:
#Write a Python program that takes a 2D NumPy array ‘arr’ as input and determine shape and dimension and add new axis
import numpy as np
arr=np.array([[1,2],[3,4]])


array([[1, 2],
       [3, 4]])

In [ ]:
arr.shape

(2, 2)

In [ ]:
arr.ndim

2

In [ ]:
arr[np.newaxis,:].shape

(1, 2, 2)

In [ ]:
'''
Write a python program to perform type conversion
a.	6.53 to int
b.	8 to float
c.	9.123 to string
'''


'\nWrite a python program to perform type conversion \na.\t6.53 to int\nb.\t8 to float\nc.\t9.123 to string\n'

In [ ]:
a=int(6.53)
a

6

In [ ]:
b=float(8)
b

8.0

In [ ]:
c=str(9.123)
c

'9.123'

In [ ]:
#Write a python program to create a dictionary with keys as even and odd numbers between 1 to 10 and calculate sum of even and odd numbers?
a_dict = {}
for i in range(1,11):
    if i%2==0:
        a_dict['even']=a_dict.get('even',0)+i
    else:
        a_dict['odd']=a_dict.get('odd',0)+i
a_dict

{'odd': 25, 'even': 30}